version: "2"

services:
  coop:
    container_name: coop
    build: 
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PRIVATE_API=$PRIVATE_API
  peon:
    container_name: peon
    build: 
        context: "."
        dockerfile: Dockerfile.peon
    volumes:
        - "./source:/app/source"
    environment:
        - AWS_JS_QUEUE=$AWS_JS_QUEUE
        - AWS_DART_QUEUE=$AWS_DART_QUEUE
    stdin_open: true
    tty: true 