name: cursor
description: Plugin for handling custom system cursors
version: 0.0.2
author:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.cursor
        pluginClass: CursorPlugin
      ios:
        pluginClass: CursorPlugin
      macos:
        pluginClass: CursorPlugin
      web:
        pluginClass: CursorPlugin
        fileName: system_cursor_web.dart
