name: rive_api_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive_api:
    path: ../
  local_data:
    path: ../../local_data



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/Roboto-Regular.ttf