
name: window_utils_macos
description: macOS implementation of the window_utils plugin.
version: 1.0.3

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowUtilsPlugin
        fileName: window_utils_macos.dart

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.8 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0