name: rive_widgets
description: Rive utility widgets shared by multiple packages.
version: 0.0.1
author:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: