name: rive_editor
description: The Rive editor written in Flutter.
version: 0.0.9

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive_core:
    path: ../rive_core/
  tree_widget:
    path: ../dependencies/tree-widget-flutter
  cursor:
    path: ../dependencies/cursor-flutter
  window_utils:
    path: ../dependencies/rive-api-flutter/dependencies/window-utils
  rive_api:
    path: ../dependencies/rive-api-flutter
  trotter: ^1.1.0
  
  # core depends on this already, do we care?
  # fractional:
  #   path: ../rive_core/dependencies/fractional-dart
  path_drawing: ^0.4.1
  dotted_border: ^1.0.4
  flutter_widgets: ^0.1.9

dev_dependencies:
  image_res: ^0.2.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/icons/
    
  uses-material-design: true
  fonts:
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
