name: peon_process
description: Flutter wrapper around peon, with some flutter specific tasks
homepage: https://rive.app/

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.4 <3.0.0"

dependencies:
  local_data:
    path: ../local_data
  peon:
    path: ../peon
  rive_core:
    path: ../rive_core
  flutter:
    sdk: flutter
  flutter_svg:
    git: 
      url: https://github.com/rive-app/flutter_svg.git
      ref: 5c765eec89aae7b166efdfc253cf583522100534
  core:
    path: ../core
  utilities: 
    path: ../utilities
  archive: ^2.0.13
  http_client: '>=0.5.0 <2.0.0'
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic: ^1.9.0

flutter:

