name: rive_core
description: Core framework for Rive.
version: 0.0.1
homepage: https://rive.app/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../dependencies/core-dart/core
  shared_preferences: ^0.5.6
  path_provider: 1.5.1
  graphs: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
