name: rive_api
description: Rive backend API for clients
version: 2.0.0
author:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  encrypt: ^4.0.0
  logging: ^0.11.4
  rxdart: ^0.24.0
  utilities:
    path: ../utilities
  local_data:
    path: ../local_data
  window_utils:
    path: ../window_utils/window_utils
  window_utils_web:
    path: ../window_utils/window_utils_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.2
  mockito: ^4.1.1

flutter: