name: coop_server_process

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  args: ^1.6.0
  colorize: ^2.0.0
  logging: ^0.11.4
  system_info: ^0.1.3

  coop_server_library:
    path: ../coop_server
  
  utilities:
    path: ../utilities