name: tree_widget
description: General tree widget
version: 0.0.1
author:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive_widgets:
    path: ../rive_widgets
  utilities:
    path: ../utilities
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: