name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      # Warning, this took a lot of massaging. Please don't mess with this unless the build is broken.
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"  
      run: |
        export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com
        ssh-agent -a $SSH_AUTH_SOCK
        echo "${{ secrets.RIVE_ENG_PRIVATE_KEY }}" > ssh.key
        chmod 600 ssh.key
        ssh-add ssh.key
        git submodule update --init --force --recursive
  
    - name: Install core dependencies
      run: cd core && pub get
  
    - name: Run core tests
      run: cd core && pub run test
