name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      run: |
        export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK
        echo ${{ secrets.RIVE_ENG_PRIVATE_KEY }} > ssh.key

  
    - name: Install core dependencies
      run: cd core && pub get
  
    - name: Run core tests
      run: cd core && pub run test
