name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup SSH Keys and known_hosts
      run: |
        export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
        mkdir -p ~/.ssh
  
    - name: Install core dependencies
      run: cd core && pub get
  
    - name: Run core tests
      run: cd core && pub run test
