name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install core dependencies
      run: cd core && pub get
    - name: Run core tests
      run: cd core && pub run test
