name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    
    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v1
  
    - name: Install core dependencies
      run: pub get
  
    - name: Run core tests
      run: pub run test