on:
    push:
      branches:
        - master
      #   - 'releases/**'
      #   - '!releases/**-alpha'
      # paths:
      #     - '**.dart'
      # tags:
      # - 'v*'

name: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup SSH Keys and known_hosts
        # Warning, this took a lot of massaging. Please don't mess with this unless the build is broken.
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com
          ssh-agent -a $SSH_AUTH_SOCK
          echo "${{ secrets.RIVE_ENG_PRIVATE_KEY }}" > ssh.key
          chmod 600 ssh.key
          ssh-add ssh.key
          git submodule update --init --force --recursive
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: cd editor && flutter pub get
      - run: cd editor && flutter test
      - run: cd editor && flutter config --enable-web
      - run: cd editor && flutter build web --release -v

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: editor/build/web

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            CHANGELOG.md

      # - name: Checkout code
      #   uses: actions/checkout@master
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release:
      #     draft: false
      #     prerelease: false
