name: Tests

on:
    pull_request:
    push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      # Install Flutter and Dart
      - name: Checkout and install flutter and dart
        run: |
          git clone https://github.com/flutter/flutter.git

      - name: Add the flutter commmand path
        run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin"

      - name: Add the dart command path
        run: echo "::add-path::$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin"

      - name: Setup flutter
        run: flutter doctor

      # Run the binary buffer tests
      - name: Install binary buffer dependencies
        run: cd packages/binary_buffer && pub get
      - name: Run binary buffer tests
        run: cd packages/binary_buffer && pub run test

      # Run the editor tests
      - name: Install editor dependencies
        run: cd packages/editor && flutter pub get
      - name: Run editor tests
        run: cd packages/editor && flutter test
    
      # Run the co-op server tests
      - name: Install coop server dependencies
        run: cd packages/coop_server && pub get
      - name: Run coop server tests
        run: cd packages/coop_server && pub run test

        # Run the core tests
      - name: Install core dependencies
        run: cd packages/core && pub get
      - name: Run core tests
        run: cd packages/core && pub run test